
project_id = "yvripyhfwglzjbaxtowl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[functions]]
name = "cora-auth"
verify_jwt = true

[[functions]]
name = "cora-boleto"
verify_jwt = true
