// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvripyhfwglzjbaxtowl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2cmlweWhmd2dsempiYXh0b3dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzI4NDEsImV4cCI6MjA1NDI0ODg0MX0.CD-GdAPYCoKLgrAIKYmtGhJrJqzH6AVtMnZv98jaKc0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);